DROP TABLE IF EXISTS test3;
CREATE TABLE test3 LIKE prep_paper3_fix_move;

ALTER TABLE test3
DROP COLUMN paper1_DV_move1,
ADD COLUMN sth INT FIRST;
#ADD COLUMN ww1 INT UNSIGNED NOT NULL AUTO_INCREMENT FIRST,
#ADD PRIMARY KEY (ww1);

LOAD DATA INFILE 'E:/Doctoral/ProjectReviews/prep_paper3_fix_move_agg10.csv' INTO TABLE test3
FIELDS TERMINATED BY ',' 
ENCLOSED BY '"'
LINES TERMINATED BY '\n';

ALTER TABLE test3
ADD COLUMN ww1 INT FIRST;

SET SQL_SAFE_UPDATES = 0;

UPDATE test3
SET ww1 = (@rownum := 1 + @rownum)
WHERE 0 = (@rownum:=0);

SET SQL_SAFE_UPDATES = 1;

ALTER TABLE test3 ADD PRIMARY KEY (ww1),
DROP COLUMN sth;

/*
ALTER TABLE `music_sample`.`test3` 
CHANGE COLUMN `sum_SI_2` `SI` DOUBLE NULL DEFAULT NULL ,
CHANGE COLUMN `sum_pop` `SI_2` DOUBLE NULL DEFAULT NULL ,
CHANGE COLUMN `sum_SI_pop` `pop` DOUBLE NULL DEFAULT NULL ,
CHANGE COLUMN `sum_SI_2_pop` `SI_pop` DOUBLE NULL DEFAULT NULL ,
CHANGE COLUMN `paper1_NA` `SI_2_pop` DOUBLE NULL DEFAULT NULL ;
*/